### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by vijay399** [yashpatel7025/PriceTracker#9]
When i Deployed to Heroku Its Showing Secret Key Not Empty so i Manually added after this Showing url.py hello,Kya after Solving this All Showing internal Server Error

**Comment by yashpatel7025** [comment]
check function name in views.py and urls.py....

**Comment by vijay399** [comment]
I Am Beginner in this Language please Make it Easy for Me, I Wasted More than 2 Days on your Project but nothing Got

**Comment by vijay399** [comment]
Another Problem is Coming from Debug Line in Settings.py, When i fill the Register or Login Form It shows Coding

**Comment by yashpatel7025** [comment]
You should know python very well brother to understand complete code, I have used advanced framework called scrapy to scrap data, if you don't know scrapy then you wont understand anything, other than this I have developed this project 2 years before to just learn new things ,so have not properly documented the project and it may take few days to understand everything
